production               :
  POCKET_CONSUMER_KEY    : <%= ENV['POCKET_CONSUMER_KEY'] %>
  READABILITY_PARSER_KEY : <%= ENV['READABILITY_PARSER_KEY'] %>
  DIFFBOT_API_KEY        : <%= ENV['DIFFBOT_API_KEY'] %>
  DELIVERY_EMAIL_SMTP    : <%= ENV['DELIVERY_EMAIL_SMTP'] %>
  DELIVERY_EMAIL_PORT    : <%= ENV['DELIVERY_EMAIL_PORT'] %>
  DELIVERY_EMAIL_ADDRESS : <%= ENV['DELIVERY_EMAIL_ADDRESS'] %>
  DELIVERY_EMAIL_PASSWORD: <%= ENV['DELIVERY_EMAIL_PASSWORD'] %>
  MANDRILL_API_KEY       : <%= ENV['MANDRILL_API_KEY'] %>
  DATABASE_HOST          : <%= ENV['DATABASE_HOST'] %>
  DATABASE_USERNAME      : <%= ENV['DATABASE_USERNAME'] %>
  DATABASE_PASSWORD      : <%= ENV['DATABASE_PASSWORD'] %>
  APP_PATH               : <%= ENV['APP_PATH'] %>
  POCKET_REDIRECT_URI    : <%= ENV['POCKET_REDIRECT_URI'] %>
